### ISSUE TITLE
Issue on page /notebooks/workflows/FLOODS/FLOOD_RIVER.html

### ISSUE THREAD

**Issue by Ankur7292** [CLIMAAX/crabook#4]
Hello,
I was trying to replicate the risk workflow for flood river and wanted to know where I can find/access the JRC_damage_curves.csv file that has been used in the analysis.

**Comment by milanavuckovic** [comment]
Hello,
Thank you for your comment!
Sorry for the delay in answering. Please use the risk workflows **from the GitHub repository** and not by downloading individual notebook.
This feedback is very useful for us to know how potential users are using the materials. We will update the notebooks with clearer message on how to access the relevant notebooks and the accompanying files.
Best regards,
Milana Vučković
