### ISSUE TITLE
Consideration of EN ISO 1409X

### ISSUE THREAD

**Issue by Clemens-XXX** [CLIMAAX/crabook#6]
Dear Writing Team,

I just want to draw your attention to the established international standards for Climate Change Adaptation. They may be usefull to consider in drafting your handbook/Scrapbox. The relevant standards are:

- CEN ISO 14090 Adaptation to climate change — Principles, requirements and guidelines
- CEN ISO 14091 Adaptation to climate change — Guidelines on vulnerability, impacts and risk assessment
- ISO/TS 14092 Adaptation to climate change — Requirements and guidance on adaptation planning for local governments and communities

As you see two of them are allread take over as European Standards (CEN). The third one is expected to follow. You will see, they are general enough to fill in with your much more detailed guides and data. There is key advantage in allinging with this standards especially with the terms, the structure/workflow and the kind of communication documents. That will help make climate change adaptation more accessible for users on the ground and can enshure compatiblity of your work with other efford by third parties (e.g. Reporting under EU Taxonomy, National handboooks and guidelines on CC Adaptation, Funding schemes for adatation measures, other EU projects, UN Guidelines etc) 

kidn regards
Clemens Haße, from EPA Germany/UBA

**Comment by milanavuckovic** [comment]
Dear Clemens,
Many thanks for your comments and for pointing out to the standards.
As this was already answered by email, I will close the issue.
Do not hesitate to contact us about any other issue.

Best regards,
Milana Vuckovic
